export const ADMIN_ROUTE = '/Admin'
export const LOGIN_ROUTE = '/Login'
export const REGISTRATION_ROUTE = '/Registration'
export const SHOP_ROUTE = '/Shop'
export const BASKET_ROUTE = '/Basket'
export const PRODUCT_ROUTE = '/Product'